//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaClase02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int id_empleado { get; set; }
        public string Empl_nombre { get; set; }
        public string Empl_apellido { get; set; }
        public string Empl_DUI { get; set; }
        public string Empl_direccion { get; set; }
        public string Empl_tel { get; set; }
        public string Empl_email { get; set; }
        public string Empl_cargo { get; set; }
    }
}
